name: Update Snake

on:
  push:
    branches:
      - main

jobs:
  update-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate snake
        uses: Platane/snk@v2.1.0
        with:
          github_user_name: gofuckbiz
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update snake" || echo "No changes to commit"
          git push
